### PR TITLE
chore: add text

### PR DESCRIPTION
**Pull request by LoskoMiguel**
chore: add text

### CODE REVIEW

**Comment by LoskoMiguel** [comment]
adasdasdas

**Comment by KevinHernandez11** [comment]
hola pichurria

**Comment by LoskoMiguel** [comment]
ey

**Comment by LoskoMiguel** [comment]
aceptala
hq720

**Comment by LoskoMiguel** [comment]
oe kevin mirame

**Comment by LoskoMiguel** [comment]
images

**Pull request merged**
